"""Add payee field to reebill_customer

Revision ID: 11f17961314c
Revises: 100f25ab057f
Create Date: 2015-04-23 17:11:48.808773

"""

# revision identifiers, used by Alembic.
revision = '11f17961314c'
down_revision = '100f25ab057f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reebill_customer', sa.Column('payee', sa.String(length=100), nullable=False, default='Nextility'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reebill_customer', 'payee')
    ### end Alembic commands ###
