"""made address field non nullable

Revision ID: 2d5527ff438a
Revises: 5999376fe57d
Create Date: 2015-11-19 17:55:52.995687

"""

# revision identifiers, used by Alembic.
revision = '2d5527ff438a'
down_revision = '5999376fe57d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reebill_customer', 'billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reebill_customer', 'service_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reebill_customer', 'service_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reebill_customer', 'billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
