"""changed type of price to numeric

Revision ID: 2f0fca54f119
Revises: 366f5ed78b68
Create Date: 2016-01-04 12:27:07.364248

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.mysql import NUMERIC, FLOAT

revision = '2f0fca54f119'
down_revision = '366f5ed78b68'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Rate_Matrix', 'Supplier_Price_Dollars_KWH_Therm', nullable=False, type_=NUMERIC(precision=10, scale=7))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Rate_Matrix', 'Supplier_Price_Dollars_KWH_Therm', nullable=False, type_=FLOAT)
    ### end Alembic commands ###
