"""test

Revision ID: 32b0a5fe5074
Revises: 4bc721447593
Create Date: 2014-11-13 14:23:35.332837

"""

# revision identifiers, used by Alembic.
revision = '32b0a5fe5074'
down_revision = '4bc721447593'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'charge', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'charge', 'group',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'charge', 'rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column(u'charge', 'rsi_binding',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'charge', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=False)
    op.alter_column(u'payment', 'date_applied',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column(u'rate_class', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'reading', 'aggregate_function',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False,
               existing_server_default='SUM')
    op.alter_column(u'reading', 'reebill_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'reading', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=False)
    op.alter_column(u'reebill', 'issued',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column(u'reebill', 'version',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'reebill_charge', 'rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column(u'reebill_charge', 'reebill_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'reebill_charge', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=False)
    op.alter_column(u'supplier', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'utilbill', 'utility_account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'utilbill', 'utility_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'utility_account', 'fb_billing_address_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'utility_account', 'fb_service_address_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'utility_account', 'fb_supplier_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utility_account', 'fb_service_address_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utility_account', 'fb_rate_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utility_account', 'fb_billing_address_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utilbill', 'utility_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utilbill', 'utility_account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utilbill', 'supplier_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'utilbill', 'rate_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'supplier', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'reebill_charge', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=True)
    op.alter_column(u'reebill_charge', 'reebill_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'reebill_charge', 'rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column(u'reebill', 'version',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'reebill', 'issued',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column(u'reading', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=True)
    op.alter_column(u'reading', 'reebill_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'reading', 'aggregate_function',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True,
               existing_server_default='SUM')
    op.alter_column(u'rate_class', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'payment', 'date_applied',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column(u'company', 'guid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column(u'charge', 'unit',
               existing_type=mysql.ENUM(u'kWh', u'dollars', u'KWD', u'therms', u'MMBTU', u'BTU'),
               nullable=True)
    op.alter_column(u'charge', 'total',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column(u'charge', 'rsi_binding',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'charge', 'rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column(u'charge', 'quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column(u'charge', 'group',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'charge', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
