"""schema_27

Revision ID: 3e4ceae0f397
Revises: 100f25ab057f
Create Date: 2015-04-20 16:42:41.513685

"""

# revision identifiers, used by Alembic.
revision = '3e4ceae0f397'
down_revision = '100f25ab057f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.create_table(
        'reebill_user',
        sa.Column('reebill_user_id', sa.Integer(), nullable=False),
        sa.Column('identifier', sa.String(length=100), nullable=False,
                  unique=True),
        sa.Column('username', sa.String(length=1000), nullable=False),
        sa.Column('preferences', sa.String(length=1000), nullable=True),
        sa.Column('session_token', sa.String(length=1000), nullable=True),
        sa.Column('password_hash', sa.String(1000), nullable=False),
        sa.Column('salt', sa.String(1000), nullable=False),
        sa.PrimaryKeyConstraint('reebill_user_id')
    )
    op.add_column('reebill_customer', sa.Column('payee', sa.String(length=100), nullable=True))

    op.create_table('be_user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('last_request', sa.DateTime(), nullable=True),
    sa.Column('billentry_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billentry_user_id'], ['billentry_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('be_user_session')
    op.drop_column('reebill_customer', 'payee')
    op.drop_table('reebill_user')


