"""adding_register_table

Revision ID: 3f16438c6c50
Revises: 55e7e5ebdd29
Create Date: 2014-05-28 15:52:06.491897

"""

# revision identifiers, used by Alembic.
revision = '3f16438c6c50'
down_revision = '3147aa982e03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilbill_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_units', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('reg_type', sa.String(length=255), nullable=False),
    sa.Column('register_binding', sa.String(length=255), nullable=False),
    sa.Column('active_periods', sa.String(length=2048), nullable=True),
    sa.Column('meter_identifier', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['utilbill_id'], ['utilbill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
