"""Added supply_group

Revision ID: 44557759112a
Revises: 100f25ab057f
Create Date: 2015-04-28 16:31:50.623556

"""

# revision identifiers, used by Alembic.
revision = '44557759112a'
down_revision = '100f25ab057f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('gas', 'electric'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('utilbill', sa.Column('supply_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilbill', 'supply_group_id')
    op.drop_table('supply_group')
    ### end Alembic commands ###
