"""increased the size of the name field of bilentry_role table

Revision ID: 44b3d2dcc1d3
Revises: 52a7069819cb
Create Date: 2015-03-24 18:49:12.633129

"""

# revision identifiers, used by Alembic.
revision = '44b3d2dcc1d3'
down_revision = '52a7069819cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billentry_role', 'name',
               existing_type=mysql.VARCHAR(length=10),
               type_=mysql.VARCHAR(length=20))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billentry_role', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=mysql.VARCHAR(length=10))
    ### end Alembic commands ###
