"""Added roles for billentry_user

Revision ID: 52a7069819cb
Revises: 4d14d767bf3a
Create Date: 2015-03-02 17:12:41.880931

"""

# revision identifiers, used by Alembic.
revision = '52a7069819cb'
down_revision = '150d8bb1183c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billentry_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('billentry_role_user',
    sa.Column('billentry_user_id', sa.Integer(), nullable=False),
    sa.Column('billentry_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billentry_user_id'], ['billentry_user.id'], ),
    sa.ForeignKeyConstraint(['billentry_role_id'], ['billentry_role.id'], ),
    sa.PrimaryKeyConstraint('billentry_user_id', 'billentry_role_id')
    )
    op.add_column('billentry_user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billentry_user', 'authenticated')
    op.drop_table('billentry_role_user')
    op.drop_table('billentry_role')
    ### end Alembic commands ###
