"""changed enum for charge.type

Revision ID: 572b9c75caf3
Revises: 556352363426
Create Date: 2015-01-23 17:12:43.834154

"""

# revision identifiers, used by Alembic.
revision = '572b9c75caf3'
down_revision = '556352363426'

from alembic import op
import sqlalchemy as sa


old_type = sa.Enum('supply', 'distribution', 'other')
new_type = sa.Enum('supply', 'distribution')

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge', u'type', type_=new_type,
                    existing_type=old_type)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge', u'type', type_=old_type,
                    existing_type=new_type)
    ### end Alembic commands ###
