"""move service to rate_class

Revision ID: 5a356721c95e
Revises: 572b9c75caf3
Create Date: 2015-02-03 17:54:26.069864

"""

# revision identifiers, used by Alembic.
revision = '5a356721c95e'
down_revision = '572b9c75caf3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_class',
            sa.Column('service', sa.Enum('gas', 'electric'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_class', 'service')
    ### end Alembic commands ###
