"""Added flagged_by to BEUtilBill

Revision ID: 686dfe445fd
Revises: 49b8d9978d7e
Create Date: 2015-07-14 13:29:35.247987

"""

# revision identifiers, used by Alembic.
revision = '686dfe445fd'
down_revision = '49b8d9978d7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilbill', sa.Column('flagged_by_id', sa.Integer(), sa.ForeignKey('billentry_user.id'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilbill', 'flagged_by_id')
    ### end Alembic commands ###
