"""customer and utilbill columns

Revision ID: 2a89489227e
Revises: 3f16438c6c50
Create Date: 2014-05-30 15:09:27.644307

"""

# revision identifiers, used by Alembic.
revision = '2a89489227e'
down_revision = '3f16438c6c50'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column(u'customer', sa.Column('fb_billing_address_id', sa.Integer(), nullable=False))
    op.add_column(u'customer', sa.Column('fb_rate_class', sa.String(length=255), nullable=False))
    op.add_column(u'customer', sa.Column('fb_service_address_id', sa.Integer(), nullable=False))
    op.add_column(u'customer', sa.Column('fb_utility_name', sa.String(length=255), nullable=False))
    op.drop_column(u'customer', 'utilbill_template_id')

    op.add_column(u'utilbill', sa.Column('billing_address_id', sa.Integer(), nullable=False))
    op.add_column(u'utilbill', sa.Column('service_address_id', sa.Integer(), nullable=False))

def downgrade():

    op.drop_column(u'utilbill', 'service_address_id')
    op.drop_column(u'utilbill', 'billing_address_id')

    op.add_column(u'customer', sa.Column('utilbill_template_id', mysql.VARCHAR(length=24), nullable=False))
    op.drop_column(u'customer', 'fb_utility_name')
    op.drop_column(u'customer', 'fb_service_address_id')
    op.drop_column(u'customer', 'fb_rate_class')
    op.drop_column(u'customer', 'fb_billing_address_id')

