"""Added processed column to reebill table

Revision ID: 4f2f8e2f7cd
Revises: 55e7e5ebdd29
Create Date: 2014-05-29 11:02:46.115863

"""

# revision identifiers, used by Alembic.
revision = '4f2f8e2f7cd'
down_revision = '55e7e5ebdd29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'reebill', sa.Column('processed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'reebill', 'processed')
    ### end Alembic commands ###
